### ISSUE TITLE
Bug w movemencie Małpy

### ISSUE THREAD

**Issue by Sharashino** [PlatWalker/game-jbzd#5]
* Małpa nie może zbliżyć się do gracza. Kiedy podejdzie na odpowiedni dystans, zatrzymuje się. Gdy gracz wtedy podejdzie w jej stronę, zacznie ją odpychać.

**Comment by PlatWalker** [comment]
No jak dla mnie działa dobrze. Wstrzymajmy się z potencjalnym naprawianiem dopóki nie zostaną dodane animacje
